# Generated by Django 3.1.4 on 2021-01-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210110_1703'),
        ('announcement', '0002_announcements_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.city'),
        ),
    ]
