# Generated by Django 3.1.4 on 2021-01-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20210116_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
