# Generated by Django 3.1.4 on 2021-01-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbuser',
            old_name='is_blocked',
            new_name='is_verify',
        ),
    ]
