# Generated by Django 3.1.4 on 2021-01-16 20:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('publish', 'publish'), ('no_publish', 'no_publish')], default='no_publish', max_length=10)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcements')),
            ],
        ),
    ]
