# Generated by Django 3.1.4 on 2021-02-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_auto_20210131_1742'),
        ('moderation', '0003_moderation_info_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='announcement',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcements'),
        ),
    ]
