# Generated by Django 3.1.4 on 2021-01-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20210110_1703'),
        ('places', '0002_auto_20210110_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Counties',
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.region'),
        ),
    ]
